name = "ReplMaker"
uuid = "b873ce64-0db9-51f5-a568-4457d8e49576"
authors = ["MasonProtter <mason.protter@gmail.com>"]
version = "0.2.7"

[deps]
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1"
